<a href="https://colab.research.google.com/github/tejaswishetty17/Large-Language-Models-Step-by-Step/blob/main/2_Tokens_and_Toekn_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q transformers sentence-transformers gensim scikit-learn>=1.5.0 accelerator>0.31.0

Load our model onto the GPU for faster inference. We will be using small model - microsoft/Phi-3-mini-4k-instruct.

Lets see how we load the model and tokenizer separately. So we can explore them separately.

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

#Load model and tokenizer

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map = "cuda",
    torch_dtype = "auto",
    trust_remote_code = False,
)

tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

In [10]:
prompt = "What is LLM? also, explain what is the use of Langchain?"

#tokenize the input prompt

input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

#Generate the text
output_generated = model.generate(
    input_ids = input_ids,
    max_new_tokens = 20
)

#print the generated output
print(tokenizer.decode(output_generated[0]), "\n\nThe input ids are:\n", input_ids)

What is LLM? also, explain what is the use of Langchain?

LLM stands for Large Language Model. It is a type of artificial intelligence model that 

The input ids are:
 tensor([[ 1724,   338,   365, 26369, 29973,   884, 29892,  5649,   825,   338,
           278,   671,   310, 10476, 14153, 29973]], device='cuda:0')


In [12]:
for id in input_ids[0]:
  print(tokenizer.decode(id))

What
is
L
LM
?
also
,
explain
what
is
the
use
of
Lang
chain
?


In [17]:
output_generated[0]

tensor([[ 1724,   338,   365, 26369, 29973,   884, 29892,  5649,   825,   338,
           278,   671,   310, 10476, 14153, 29973,    13,    13,  2208, 29924,
         15028,   363,  8218,   479, 17088,  8125, 29889,   739,   338,   263,
          1134,   310, 23116, 21082,  1904,   393]], device='cuda:0')

In [22]:
for id in output_generated[0]:
  print("generated_id: ",id, "Genearted item:" ,tokenizer.decode(id))

generated_id:  tensor(1724, device='cuda:0') Genearted item: What
generated_id:  tensor(338, device='cuda:0') Genearted item: is
generated_id:  tensor(365, device='cuda:0') Genearted item: L
generated_id:  tensor(26369, device='cuda:0') Genearted item: LM
generated_id:  tensor(29973, device='cuda:0') Genearted item: ?
generated_id:  tensor(884, device='cuda:0') Genearted item: also
generated_id:  tensor(29892, device='cuda:0') Genearted item: ,
generated_id:  tensor(5649, device='cuda:0') Genearted item: explain
generated_id:  tensor(825, device='cuda:0') Genearted item: what
generated_id:  tensor(338, device='cuda:0') Genearted item: is
generated_id:  tensor(278, device='cuda:0') Genearted item: the
generated_id:  tensor(671, device='cuda:0') Genearted item: use
generated_id:  tensor(310, device='cuda:0') Genearted item: of
generated_id:  tensor(10476, device='cuda:0') Genearted item: Lang
generated_id:  tensor(14153, device='cuda:0') Genearted item: chain
generated_id:  tensor(29973,

#Comparing the LLM Tokenizers

In [66]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '44;127;117',  # Dark Teal
    '215;48;39',   # Brick Red
    '117;107;177', # Muted Purple
    '175;141;195', # Lavender Gray
    '102;194;165', # Soft Teal
    '128;128;0'    # Olive
]

def show_tokens(sentence, tokenizer_name):
  try:
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
  except Exception as e:
    print(f"Error loading tokenizer:{e}")
    return

  encoded = tokenizer(sentence, return_tensors="pt")
  token_ids = encoded.input_ids[0].tolist()
  tokens = tokenizer.convert_ids_to_tokens(token_ids)

  for idx, t in enumerate(tokens):
    color = colors_list[idx % len(colors_list)]
    print(
        f'\x1b[0;30;48;2;{color}m{t}\x1b[0m',
        end=' '
    )

In [64]:
text = """
What is the LLM? What is the use of Langchain? What are the models available in LLM?

show_output False if n >= 700 else: use the input from user: " "

15*855+3
"""

In [50]:
show_tokens(text, "bert-base-uncased")

[CLS] what is the ll ##m ? what is the use of lang ##chai ##n ? what are the models available in ll ##m ? show _ output false if n > = 700 else : use the input from user : " " 15 * 85 ##5 + 3 [SEP] 

In [51]:
show_tokens(text, "bert-base-cased")

[CLS] What is the LL ##M ? What is the use of Lang ##cha ##in ? What are the models available in LL ##M ? show _ output F ##als ##e if n > = 700 else : use the input from user : " " 15 * 85 ##5 + 3 [SEP] 

In [55]:
show_tokens(text, "gpt2")

Ċ What Ġis Ġthe ĠLL M ? ĠWhat Ġis Ġthe Ġuse Ġof ĠLang chain ? ĠWhat Ġare Ġthe Ġmodels Ġavailable Ġin ĠLL M ? Ċ Ċ show _ output ĠFalse Ġif Ġn Ġ>= Ġ700 Ġelse : Ġuse Ġthe Ġinput Ġfrom Ġuser : Ġ" Ġ" Ċ Ċ 15 * 855 + 3 Ċ 

In [57]:
show_tokens(text, "google/flan-t5-small")

▁What ▁is ▁the ▁L LM ? ▁What ▁is ▁the ▁use ▁of ▁Lang chain ? ▁What ▁are ▁the ▁models ▁available ▁in ▁L LM ? ▁show _ out put ▁Fal s e ▁ if ▁ n ▁> = ▁700 ▁else : ▁use ▁the ▁input ▁from ▁user : ▁" ▁" ▁15 * 85 5 + 3 ▁ </s> 

In [59]:
show_tokens(text, "bigcode/starcoder2-15b")

Ċ What Ġis Ġthe ĠLL M ? ĠWhat Ġis Ġthe Ġuse Ġof ĠLang chain ? ĠWhat Ġare Ġthe Ġmodels Ġavailable Ġin ĠLL M ? Ċ Ċ show _ output ĠFalse Ġif Ġn Ġ>= Ġ 7 0 0 Ġelse : Ġuse Ġthe Ġinput Ġfrom Ġuser : Ġ" Ġ" ĊĊ 1 5 * 8 5 5 + 3 Ċ 

In [68]:
show_tokens(text, "xenova/gpt-4")

Ċ What Ġis Ġthe ĠL LM ? ĠWhat Ġis Ġthe Ġuse Ġof ĠLang chain ? ĠWhat Ġare Ġthe Ġmodels Ġavailable Ġin ĠL LM ?ĊĊ show _output ĠFalse Ġif Ġn Ġ>= Ġ 700 Ġelse : Ġuse Ġthe Ġinput Ġfrom Ġuser : Ġ" Ġ"ĊĊ 15 * 855 + 3 Ċ 

In [69]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

▁ <0x0A> What ▁is ▁the ▁L LM ? ▁What ▁is ▁the ▁use ▁of ▁Lang chain ? ▁What ▁are ▁the ▁models ▁available ▁in ▁L LM ? <0x0A> <0x0A> show _ output ▁False ▁if ▁n ▁>= ▁ 7 0 0 ▁else : ▁use ▁the ▁input ▁from ▁user : ▁" ▁" <0x0A> <0x0A> 1 5 * 8 5 5 + 3 <0x0A> 

In [71]:
show_tokens(text, "facebook/galactica-1.3b")

Ċ What Ġis Ġthe ĠLL M ? ĠWhat Ġis Ġthe Ġuse Ġof ĠLang chain ? ĠWhat Ġare Ġthe Ġmodels Ġavailable Ġin ĠLL M ? Ċ Ċ show _ output ĠFalse Ġif Ġn Ġ > = Ġ 7 0 0 Ġelse : Ġuse Ġthe Ġinput Ġfrom Ġuser : Ġ " Ġ " Ċ Ċ 1 5 * 8 5 5 + 3 Ċ 




#Contextualized Word Embeddings from a Language Model (BERT)

In [75]:
from transformers import AutoTokenizer, AutoModel

#load the tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

#load the language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

#Tokenize the sentence
tokens = tokenizer("What is the use of LLM?", return_tensors="pt")

#process the tokens
output = model(**tokens)[0]

print(output)

tensor([[[-3.4084, -0.0206,  0.0135,  ..., -0.1310, -0.2714,  0.4145],
         [ 0.0888, -0.1408,  0.9285,  ...,  1.0939,  0.1736, -0.8977],
         [-0.6695,  0.5729, -0.0083,  ...,  1.4061, -0.2961,  1.9668],
         ...,
         [-0.5664,  0.1876,  0.5035,  ...,  0.2483,  0.1360,  0.0345],
         [-1.3494, -0.5803,  0.0978,  ...,  0.8251, -0.0277, -0.8503],
         [-3.2909,  0.0297,  0.1384,  ..., -0.1615, -0.3223,  0.0467]]],
       grad_fn=<NativeLayerNormBackward0>)


In [76]:
output.shape

torch.Size([1, 10, 384])

In [77]:
for token in tokens['input_ids'][0]:
  print(tokenizer.decode(token))

[CLS]
What
 is
 the
 use
 of
 LL
M
?
[SEP]


#Text Embedding(Sentence and full documnets)

In [80]:
from sentence_transformers import SentenceTransformer

#Load the model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

#Convert the text to text embedding
vector = model.encode("What is the use of Langchain?")

In [81]:
vector.shape

(768,)

#Word embedding beyond LLMs


In [11]:
import gensim.downloader as api

# use glove embeddings which is trained on wikipedia, vector size : 50)
# word2vec-google-news-300 is another option

model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [ ]:
model_2 = api.load("word2vec-google-news-300")

In [88]:
model.most_similar([model['aeroplanes']], topn=10)

[('aeroplanes', 1.0000001192092896),
 ('gliders', 0.776185929775238),
 ('muskets', 0.7652149796485901),
 ('machine-guns', 0.7167890071868896),
 ('b-29s', 0.7126129865646362),
 ('hovercraft', 0.7082041501998901),
 ('cruisers', 0.7070890069007874),
 ('seaplanes', 0.7065178751945496),
 ('self-propelled', 0.7062690854072571),
 ('aircrafts', 0.7022036910057068)]

In [90]:
model_2.most_similar([model_2['India']], topn=11)

[('India', 1.0000001192092896),
 ('Indias', 0.7384199500083923),
 ('Indiaâ_€_™', 0.6843486428260803),
 ('Pakistan', 0.6706861257553101),
 ('Delhi', 0.6632035970687866),
 ('Bangalore', 0.6583030819892883),
 ('subcontinent', 0.6579218506813049),
 ('Bangladesh', 0.6527796983718872),
 ('sub_continent', 0.650303840637207),
 ('Mumbai', 0.6495688557624817),
 ('Sri_Lanka', 0.6445952653884888)]

#Recommending Movies by embeddings

In [12]:
import pandas as pd
from urllib import request

#Get the movies dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

#Parse the playlist dataset file. Skip the first two lines as thet contain metadata

lines = data.read().decode("utf-8").split('\n')[2:]

#Remove the playlist with only one song
playlist = [s.rstrip().split() for s in lines if len(s.split())>1]

#Load song metadata
song_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
song_file = song_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in song_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [8]:
songs_df.head()

title      artist
id                                                               
0                        Gucci Time (w\/ Swizz Beatz)  Gucci Mane
1   Aston Martin Music (w\/ Drake & Chrisette Mich...   Rick Ross
2                       Get Back Up (w\/ Chris Brown)        T.I.
3                  Hot Toddy (w\/ Jay-Z & Ester Dean)       Usher
4                                        Whip My Hair      Willow

In [4]:
print("playlist1: ", playlist[0], "\n","playlist2: ", playlist[1])

playlist1:  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 
 playlist2:  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118'

In [15]:
from gensim.models import Word2Vec

#train our Word2Vec model

model = Word2Vec(
    playlist, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [24]:
song_id = 3892

#check the model for songs similar to #357
model.wv.most_similar(positive=str(song_id))

[('7325', 0.9936237931251526),
 ('8484', 0.9932810664176941),
 ('16522', 0.9932749271392822),
 ('4117', 0.9927000403404236),
 ('3936', 0.9926295876502991),
 ('4193', 0.9920005798339844),
 ('3850', 0.9918624758720398),
 ('3760', 0.9918587803840637),
 ('3480', 0.9914047718048096),
 ('8593', 0.991335928440094)]

In [25]:
print(songs_df.iloc[3892])

title     Borderline
artist       Madonna
Name: 3892 , dtype: object


In [31]:
import numpy as np

def print_recommendations(song_id):
  similar_songs = np.array(
      model.wv.most_similar(positive=str(song_id), topn=5)
  )[:,0]
  print(similar_songs)
  return songs_df.iloc[similar_songs]

print_recommendations(3892)

['7325' '8484' '16522' '4117' '3936']


title           artist
id                                                                        
7325                                           You And Me        Lifehouse
8484                          Flashdance...What A Feeling       Irene Cara
16522                                             Beat It  Michael Jackson
4117    I've Had The Time Of My Life (W\/ Jennifer War...      Bill Medley
3936                                        Forever Young      Rod Stewart

In [27]:
print_recommendations(4200)

title        artist
id                                              
15659           Promises, Promises    Naked Eyes
3629                  Don't Change          INXS
3761                       Too Shy    Kajagoogoo
4144                When It's Over     Sugar Ray
3379    Things Can Only Get Better  Howard Jones

In [28]:
print_recommendations(85)

title           artist
id                                                              
20064                                       S&M          Rihanna
82                     Only Girl (In The World)          Rihanna
14      DJ Got Us Fallin' In Love (w\/ Pitbull)            Usher
19471                  The Time (The Dirty Bit)  Black Eyed Peas
13973                          No Woman, No Cry       The Fugees